deploy:
  provider: rubygems
  api_key:
    secure: ayNLN94W/7OLlrbpOgszFYfx7cvhAYHLcW9NZG/gN4N0kUiwZ5f7vGGT2YDPSjiXdxLDnZfCdO5gmMjP59XyWqq4n3HxG5PipsZ5HjOp+nuUh/PzPB7YXizFCjGm9ggIUrBcE3pdrD7hYuKmMlnDjnAcgOQn+zw+QHNGmV3mJhSNuo+Vp/GotU8aAITHCQZUsSMQZQMGjoGG5yf+BAhJSf+mpPBNIoqdI/di8W2rzynwQJeN19/O7M1evAyt/vFVgNlwBE2YaEc7RWn3fhWV6O7nJSFTbGEv5gsMZYPRRWrw2DvBfnhCD4T3jC/hfuMybOUNbF9waktaxKeWVvKiYqQsDPYoh/3H/PViU/sFwKbU2jsxqAUkIBA5yhQXYk4FcKBUInHAIQE3dGy0eBa+hGC0u6sC9mwy3OFWiAfIPU8Fq+dW6e8N7ebJ1NW2UOxJLZjO2AS4LB2A2pMn/wTwm+ru3gVWqM3CF6vr4nc/hpj7DIFuI0OVDLNLeBzfV0Q8frxW8HoYgO2S/7RKXlT5PvwE+6pES2EEADa6LblZCVv6pu0VzVmuUNJ51HkUNYuCHIubXpyJBJGaFpG35q+u05Dh6MPVb+ZtSdNlG9Mw4Rcwpn6rE77+Mkh0TQ1q39SSO1odI6wONi6KTatuK56tV4tTL1fQBgtzYA4Gfl6z+OA=
  on:
    tags: true
  gem: et_full_system
install:
